[project]
name = "liquidx"
description = "LiquidX - Incentivized Bridge Aggregator for USDCx on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
boot_contracts = []

[contracts.liquidity-rewards]
path = "contracts/liquidity-rewards.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
